CREATE TABLE Observer(
    tg_id BIGINT PRIMARY KEY,
    first_name TEXT,
    last_name TEXT,
    uik INT CHECK ( uik > 0 )
);

CREATE TABLE Invitation(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code TEXT UNIQUE NOT NULL,
    observer_id BIGINT REFERENCES Observer
);

CREATE TABLE DialogStateEnum(
    id INT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE DialogState(
    observer_id BIGINT NOT NULL REFERENCES Observer PRIMARY KEY,
    state_id INT REFERENCES DialogStateEnum,
    data TEXT
);

INSERT INTO DialogStateEnum(id, value) VALUES
(1, 'Ожидаю ввода номера УИК'), (2, 'Ожидаю ввода количества надомной досрочки'),
(3, 'Ожидаю ввода количества стационарной досрочки'), (4, 'Ожидаю пересылки документов'),
(5, ''), (6, ''), (7, ''), (8, ''), (9, '')
ON CONFLICT DO NOTHING;

--DROP TABLE DialogState CASCADE;
--DROP TABLE DialogStateEnum;
--DROP TABLE VotersCount;
CREATE TABLE VotersCount(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    observer_id BIGINT NOT NULL REFERENCES Observer,
    uik INT NOT NULL,
    election_date DATE NOT NULL,
    safe_num INT NOT NULL,
    voters_cnt INT CHECK ( voters_cnt>= 0 ),
    box_num INT,
    voting_type INT CHECK ( voting_type between 0 and 1),
    airtable_record_id TEXT UNIQUE,
    UNIQUE (observer_id, uik, election_date, safe_num)
);

--DROP TABLE VotersCountDocument;
CREATE TABLE VotersCountDocument(
    voters_count_id INT NOT NULL REFERENCES VotersCount,
    doc_id TEXT NOT NULL
);

INSERT INTO Invitation(code) VALUES ('товарищ'), ('звезда'), ('счастье'),
                                    ('сон'), ('обломок'), ('самовластье'), ('имя');

