CREATE TABLE Observer(
    tg_id BIGINT PRIMARY KEY,
    first_name TEXT,
    last_name TEXT,
    uik INT CHECK ( uik > 0 )
);

CREATE TABLE Invitation(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code TEXT UNIQUE NOT NULL,
    observer_id BIGINT REFERENCES Observer
);

CREATE TABLE DialogStateEnum(
    id INT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE DialogState(
    observer_id BIGINT NOT NULL REFERENCES Observer PRIMARY KEY,
    state_id INT REFERENCES DialogStateEnum,
    data TEXT
);

INSERT INTO DialogStateEnum(id, value) VALUES
(1, 'Ожидаю ввода номера УИК'), (2, 'Ожидаю ввода количества надомной досрочки'),
(3, 'Ожидаю ввода количества стационарной досрочки'), (4, 'Ожидаю пересылки документов')
ON CONFLICT DO NOTHING;

--DROP TABLE DialogState CASCADE;
--DROP TABLE DialogStateEnum;
DROP TABLE VotersCount;
CREATE TABLE VotersCount(
    observer_id BIGINT NOT NULL REFERENCES Observer,
    uik INT NOT NULL,
    election_date DATE NOT NULL,
    home_voters INT CHECK ( home_voters >= 0 ),
    uik_voters INT CHECK ( uik_voters>= 0 ),
    airtable_record_id TEXT UNIQUE,
    PRIMARY KEY (observer_id, uik, election_date)
);

DROP TABLE VotersCountDocument;
CREATE TABLE VotersCountDocument(
    observer_id BIGINT NOT NULL REFERENCES Observer,
    uik INT NOT NULL,
    election_date DATE NOT NULL,
    doc_id TEXT NOT NULL,
    FOREIGN KEY(observer_id, uik, election_date) REFERENCES VotersCount
);

INSERT INTO Invitation(code) VALUES ('товарищ'), ('звезда'), ('счастье'),
                                    ('сон'), ('обломок'), ('самовластье'), ('имя');

