# Pull base image
FROM tomcat:9-jdk8-corretto

# Maintainer
MAINTAINER "Наблюдатели Петербурга <spbelect@gmail.com">

# Copy to images tomcat path
ADD build/libs/backend.war /usr/local/tomcat/webapps/ROOT.war
